#!/bin/sh

commands="\
open in browser
play in mpv
queue for download\
"

choice="$(echo "$commands" | dmenu -p "What would you like to do?")" || exit 1

playvid() {
	notify-send "📹 launching video..." "$1"
#	mpv --ytdl-raw-options=format="best[height=720]" "$1" || \
	setsid -f mpv "$1" || notify-send "📹❗ playback failed!" "$1"
}

case $choice in
	"open in browser")	setsid -f "$BROWSER" "$1" ;;
	"play in mpv")          playvid "$1" ;;
	"queue for download")	qndl "$1" & ;;
esac
